<!doctype html>
    <html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php if(isset($titulo)) {
            echo '<title>' . $titulo . ' | Manos que Hablan Rostros que Expresan</title>';
        } else {
            echo '<title>Manos que Hablan Rostros que Expresan</title>';
        } ?>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <style>#home_pasantias,#home_quienes_somos,.formInsc{background-color:#eee}body{padding-top:60px}#col03989e{background-color:#03989e}#f1aa40{background-color:#f1aa40}#b2ebf2{background-color:#212121}.colLogo{height:auto;width:60%}.colLogo2{height:auto;width:70%}.colLogo3{height:auto;width:80%}.colInicio{height:100vh;display:flex;justify-content:center;align-items:center}#mPersonalizada{margin-top:6em}#tituloEquipo{text-decoration:none}#home_intro{background-color:#000}#home_quienes_somos{padding-top:6em;padding-bottom:7em}#home_diferencia{padding-top:9em;color:#000;background-color:#fff;background:repeating-linear-gradient(-45deg,#03999e07,#03999e10 5px,#fff 5px,#fff 25px);padding-bottom:4em}#home_interpretaciones{padding-top:9em;padding-bottom:5em;background-color:#03989e20}#home_formacion_interpretes{padding-top:10em}#home_comentarios_alumnos,#home_equipo,#home_inscripciones{padding-top:9em;padding-bottom:4em}#home_pasantias{padding-top:9em;padding-bottom:2em}#home_porque_estudiar{background-color:#00c9d40b;padding-top:10em;padding-bottom:10em}#home_contacto{padding-top:4em;padding-bottom:4em}.btn-primary-lsa,footer{background-color:#03989e;color:#fff}#informacion_formacion{margin-top:5em;margin-bottom:0}#contacto_formulario{margin-top:8em}.text-instituto{color:#03989e}.btn-primary-lsa:hover{background-color:#00cbd4;color:#fff;transition:.5s}.btn-outline-lsa{border-color:#03989e;color:#03989e;background-color:transparent}.btn-outline-lsa:hover{background-color:#03989e;color:#fff;transition:.5s}.btn-primary-turismo{background-color:#212121;color:#fff;display:inline-block}.btn-primary-turismo:hover{background-color:#313131;color:#fff;transition:.5s}.btn-primary-plataforma{background-color:#f1aa40;color:#000}.btn-primary-plataforma:hover{background-color:#ffbd5b;border-color:#ffbd5b;transition:.5s}.btn-primary-mp{background-color:#009ee3;border-color:#009ee3;color:#fff}.btn-primary-mp:hover{background-color:#008ac6;border-color:#008ac6;color:#fff}.caption-style-1{list-style-type:none;margin:0;padding:0}.caption-style-1 li{float:left;padding:0;position:relative;overflow:hidden}.caption-style-1 li:hover .caption{opacity:1}.caption-style-1 img{margin:0;padding:0;float:left;z-index:4}.caption-style-1 .caption{cursor:pointer;position:absolute;opacity:0;-webkit-transition:.45s ease-in-out;-moz-transition:.45s ease-in-out;-o-transition:.45s ease-in-out;-ms-transition:.45s ease-in-out;transition:.45s ease-in-out}.caption-style-1 .blur{background-color:rgba(0,0,0,.65);height:300px;width:100%;z-index:5;position:absolute}.caption-style-1 .caption-text h1{text-transform:uppercase;font-size:24px}.caption-style-1 .caption-text{z-index:10;color:#fff;position:absolute;width:100%;height:300px;text-align:center;top:100px}.lista-color ol{list-style:none;counter-reset:contador1}.lista-color ol li{counter-increment:contador1}.lista-color ol li::before{content:counter(contador1) ". ";color:#03989e;font-weight:700}</style>
        <link rel="stylesheet" href="ihover.min.css">
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    </head>
    <body>